version: '3.8'

services:
  ssl_spoofing_model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ../storage:/app/storage
      - ./results_csv:/app/results_csv
      - ../datasets:/app/datasets
